"""Alembic environment.

Two things are decided here.

**Where the connection string comes from.** From the process configuration, the
same one the service itself validates at startup (D54) — not from alembic.ini.
A second source of truth for the database address is the source that gets used
by accident, and a migration applied to the wrong database is not something the
next command can undo. Tests override it explicitly through
``config.set_main_option``, which is the only caller that may.

**How migrations run.** Through the async driver, because that is the driver the
service uses and the one whose behaviour must be exercised; ``run_sync`` bridges
Alembic's synchronous migration context onto it.

Autogenerate compares against ``Base.metadata``, so every model module has to be
imported before it runs — hence the models import below, which looks unused and
is not.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from identity.infrastructure.config import get_settings
from identity.infrastructure.db import models  # noqa: F401  # registers the tables on Base.metadata
from identity.infrastructure.db.base import Base

config = context.config

if config.config_file_name is not None:
    # disable_existing_loggers stays off: when Alembic is driven in-process —
    # by the integration tests, or by a future maintenance command — the
    # default would silence every logger the host process had already set up.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def database_url() -> str:
    """The URL to migrate, from the test override or from configuration."""
    override = config.get_main_option("sqlalchemy.url", default="")
    if override:
        return override
    return str(get_settings().database_dsn)


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of applying it.

    Used to review what a release will do to production before it does it.
    """
    context.configure(
        url=database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Without these, a changed column type or default is silently missing
        # from an autogenerated revision, and the schema drifts from the models.
        compare_type=True,
        compare_server_default=True,
        # One transaction for the whole upgrade: a migration that fails halfway
        # leaves the schema as it was, not in a state no code expects.
        transaction_per_migration=False,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = database_url()

    # NullPool: this process applies migrations and exits. A pool would keep
    # connections open past the last statement and delay that exit.
    engine = async_engine_from_config(configuration, prefix="sqlalchemy.", poolclass=NullPool)
    try:
        async with engine.connect() as connection:
            await connection.run_sync(do_run_migrations)
    finally:
        await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
